export interface IDesignElementConfig {
    selector?: string;
    tagName: tagType;
    id?: string;
    icon: string;
    hoverText: string;
    placeholder: string;
    cssClass?: string[];
    defaultValue: string;
    value?: unknown;
    child: IDesignElementConfig[];
    uId?: string;
    zones: Array<string>;
    forName?: string;
    parentId: string;
}

export interface IMenuList {
    heading: string;
    options: IDesignElementConfig[];
}

export type tagType =
    | 'a'
    | 'abbr'
    | 'acronym'
    | 'address'
    | 'area'
    | 'article'
    | 'aside'
    | 'audio'
    | 'b'
    | 'base'
    | 'bdi'
    | 'bdo'
    | 'big'
    | 'blockquote'
    | 'body'
    | 'br'
    | 'button'
    | 'canvas'
    | 'caption'
    | 'center'
    | 'cite'
    | 'code'
    | 'col'
    | 'colgroup'
    | 'data'
    | 'datalist'
    | 'dd'
    | 'del'
    | 'details'
    | 'dd'
    | 'dt'
    | 'del'
    | 'details'
    | 'dfn'
    | 'dialog'
    | 'dir'
    | 'div'
    | 'dl'
    | 'em'
    | 'embed'
    | 'fencedframe'
    | 'fieldset'
    | 'figcaption'
    | 'figure'
    | 'font'
    | 'footer'
    | 'form'
    | 'frame'
    | 'frameset'
    | 'head'
    | 'header'
    | 'hgroup'
    | 'hr'
    | 'html'
    | 'i'
    | 'iframe'
    | 'img'
    | 'input'
    | 'ins'
    | 'kbd'
    | 'label'
    | 'legend'
    | 'li'
    | 'link'
    | 'main'
    | 'map'
    | 'mark'
    | 'marquee'
    | 'menu'
    | 'menuitem'
    | 'h1'
    | 'h2'
    | 'h3'
    | 'h4'
    | 'h5'
    | 'h6'
    | 'meta'
    | 'meter'
    | 'nav'
    | 'nobr'
    | 'noembed'
    | 'noframes'
    | 'noscript'
    | 'object'
    | 'ol'
    | 'optgroup'
    | 'option'
    | 'ouput'
    | 'p'
    | 'param'
    | 'picture'
    | 'plaintext'
    | 'portal'
    | 'pre'
    | 'progress'
    | 'q'
    | 'rb'
    | 'rp'
    | 'rt'
    | 'rtc'
    | 'ruby'
    | 's'
    | 'samp'
    | 'script'
    | 'search'
    | 'section'
    | 'select'
    | 'slot'
    | 'small'
    | 'source'
    | 'span'
    | 'strike'
    | 'strong'
    | 'style'
    | 'sub'
    | 'table'
    | 'tbody'
    | 'td'
    | 'template'
    | 'textarea'
    | 'tfoot'
    | 'th'
    | 'thead'
    | 'time'
    | 'title'
    | 'tr'
    | 'track'
    | 'tt'
    | 'u'
    | 'ul'
    | 'var'
    | 'video'
    | 'wbr'
    | 'xmp';

// | 'span'
// | 'div'
// | 'break'
// | 'textbox'
// | 'checkbox'
// | 'radioButton'
// | 'color'
// | 'password'
// | 'number'
// | 'email'
